esphome:
  name: comfortzone
  platformio_options:
    build_flags: -D HP_PROTOCOL=180
  libraries:
    - https://github.com/vinnyspb/FastCRC.git
    - https://github.com/vinnyspb/comfortzone_heatpump.git#feature/adding_new_protocol_version
  includes:
    - esphome_rs485.h
    - comfortzone_esphome.h

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf

uart:
  id: uart_bus
  tx_pin: 35
  rx_pin: 36
  baud_rate: 19200
  data_bits: 8
  parity: NONE
  stop_bits: 1

sensor:
- platform: custom
  lambda: |-
    auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus));
    return cz->get_sensors();

  sensors:
    - name: "Days until filter change"
      unit_of_measurement: days
    - name: "Outdoor temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Flow water temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Return water temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Indoor temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Hot gas temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Exchanger out temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Evaporator in temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Exhaust air temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Hot water temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Current compressor frequency"
      unit_of_measurement: Hz
    - name: "Current compressor power"
      unit_of_measurement: W
    - name: "Current compressor additional power"
      unit_of_measurement: W
    - name: "Current compressor total power"
      unit_of_measurement: W
    - name: "Current compressor input power"
      id: current_compressor_input_power
      unit_of_measurement: W
    - name: "Current compressor heating input power"
      id: current_compressor_heating_input_power
      unit_of_measurement: W
    - name: "Current compressor water input power"
      id: current_compressor_water_input_power
      unit_of_measurement: W
    - name: "Compressor energy"
      unit_of_measurement: kWh
    - name: "Additional energy"
      unit_of_measurement: kWh
    - name: "Hot water energy"
      unit_of_measurement: kWh
    - name: "Compressor runtime"
      unit_of_measurement: min
    - name: "Total runtime"
      unit_of_measurement: min
    - name: "Room heating setting"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Hot water setting"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Fan speed duty"
      unit_of_measurement: "%"
    - name: "Hot water calculated setting"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Heating CoP"
      state_class: measurement
      accuracy_decimals: 2
    - name: "Hot Water CoP"
      state_class: measurement
      accuracy_decimals: 2
- platform: total_daily_energy
  name: "Total Daily Input Energy"
  power_id: current_compressor_input_power
- platform: total_daily_energy
  name: "Total Daily Heating Input Energy"
  power_id: current_compressor_heating_input_power
- platform: total_daily_energy
  name: "Total Daily Water Input Energy"
  power_id: current_compressor_water_input_power

binary_sensor:
  - platform: custom
    lambda: |-
      auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus));
      return cz->get_binary_sensors();
  
    binary_sensors:
      - name: "Filter alarm"
      - name: "Hot water production"
      - name: "Room heating in progress"
      - name: "Additional power enabled"
      - name: "Defrost enabled"
      - name: "Extra hot water setting"

text_sensor:
  - platform: custom
    lambda: |-
      auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus));
      return cz->get_text_sensors();
  
    text_sensors:
      - name: "Compressor activity"
      - name: "Mode"
      - name: "Fan speed"
      - name: "Hot water priority setting"

climate:
  - platform: custom
    lambda: |-
      auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus));
      return cz->get_climate_entities();

    climates:
      - name: "ComfortZone EX50 heating"
      - name: "ComfortZone EX50 hot water"

time:
  - platform: sntp
    id: sntp_time

logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
