name: Pull request check build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd $GITHUB_WORKSPACE
          python3 -m venv venv
          source venv/bin/activate
          pip install esphome
          esphome -s git_branch $GITHUB_HEAD_REF config .github/test/test-build.yaml > comfortzone-build.yaml
          esphome compile comfortzone-build.yaml
