name: Pull request check build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd $GITHUB_WORKSPACE &&
          python3 -m venv venv &&
          source venv/bin/activate &&
          pip install esphome &&
          export GIT_BRANCH=`git branch --show-current` &&
          esphome -s git_branch $GIT_BRANCH .github/test/test-build.yaml config > /tmp/comfortzone.yaml &&
          esphome compile /tmp/comfortzone.yaml
